#index:
#    path: /
#    controller: App\Controller\DefaultController::index


app_main:
    path:       /{_locale}/
    controller: App\Controller\MainController::indexAction
    requirements:
        _locale: fr|en
